[".local/share/fonts"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Iosevka.zip"
  exact = true

[".local/share/fonts"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/IosevkaTerm.zip"
  exact = true